apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: laravel-in-kubernetes-fpm
  labels:
    tier: backend
    layer: fpm
  annotations:
    configmap.reloader.stakater.com/reload: "laravel-in-kubernetes"
    secret.reloader.stakater.com/reload: "laravel-in-kubernetes"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: "henrotaym/trustup-io-website-monitoring-cli:0.0.1"
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes
      containers:
        - name: fpm
          image: "henrotaym/trustup-io-website-monitoring-fpm:d4304bd05f8ada0777c3dcb38d9ade915b3ebe81"
          command: ["/bin/sh"]
          args: [
              "-c",
              "php artisan event:cache && \
              php artisan route:cache && \
              php artisan view:cache && \
              exec php-fpm",
            ]
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes
