# For more information: https://laravel.com/docs/sail
version: '3'
services:
    trustup-io-website-monitoring:
        container_name: trustup-io-website-monitoring
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-48080}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - trustup-io-website-monitoring-sail
            - applications
        depends_on:
            - trustup-io-website-monitoring-mysql
            - trustup-io-website-monitoring-redis
    trustup-io-website-monitoring-mysql:
        container_name: trustup-io-website-monitoring-mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-43306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'trustup-io-website-monitoring-sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - trustup-io-website-monitoring-sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    trustup-io-website-monitoring-redis:
        container_name: trustup-io-website-monitoring-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-46379}:6379'
        volumes:
            - 'trustup-io-website-monitoring-sail-redis:/data'
        networks:
            - trustup-io-website-monitoring-sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    trustup-io-website-monitoring-sail:
        driver: bridge
    applications:
        name: applications
        external: true
volumes:
    trustup-io-website-monitoring-sail-mysql:
        driver: local
    trustup-io-website-monitoring-sail-mysql-testing:
        driver: local
    trustup-io-website-monitoring-sail-redis:
        driver: local
