apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate a ConfigMap based on the environment variables in the file `.env`.
configMapGenerator:
  - name: deployments-config-map
    envs:
      - .env.production

replacements:
  - source:
      # Replace any matches by the value of environment variable `MY_IMAGE_TAG`.
      kind: ConfigMap
      name: deployments-config-map
      fieldPath: data.APP_VERSION
    targets:
      - select:
          # In each Deployment resource …
          kind: Deployment
        fieldPaths:
          # - spec.template.spec.containers.[name=cron].image
          - spec.template.spec.containers.[name=fpm].image
          - spec.template.spec.containers.[name=queue-worker].image
          - spec.template.spec.containers.[name=webserver].image
          - spec.template.spec.initContainers.[name=migrations].image
        options:
          # … but replace only the second part (image tag) when split by ":".
          delimiter: ":"
          index: 1

resources:
  - app/1_common/config-map.yml
  - app/2_fpm/deployment.yml
  - app/3_webserver/deployment.yml
  - app/5_queue-workers/deployment-default.yml
  - app/6_cron/deployment.yml
