name: "production-deployment"

on:
  push:
    branches:
      - "main"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push cli image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          target: cli
          push: true
          tags: "henrotaym/trustup-io-website-monitoring-cli:${{ github.sha }}"
      - 
        name: Build and push cron image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          target: cron
          push: true
          tags: "henrotaym/trustup-io-website-monitoring-cron:${{ github.sha }}"
      - 
        name: Build and push fpm image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          target: fpm_server
          push: true
          tags: "henrotaym/trustup-io-website-monitoring-fpm:${{ github.sha }}"
      - 
        name: Build and push web image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          target: web_server
          push: true
          tags: "henrotaym/trustup-io-website-monitoring-web:${{ github.sha }}"
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - 
        name: Save DigitalOcean kubeconfig
        run: doctl k8s cluster kubeconfig save ${{ secrets.DIGITALOCEAN_KUBERNETES_CLUSTER_ID }}
      - 
        name: Trigger kubernetes deployment
        run: |
          export APP_VERSION=${{ github.sha }}
          kubectl apply -k devops/production/kubernetes
