name: "testastos"

on:
  push:
    branches:
      - "main"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: "1.79.0"
      - 
        name: Save DigitalOcean kubeconfig
        run: doctl k8s cluster kubeconfig save ${{ secrets.DIGITALOCEAN_KUBERNETES_CLUSTER_ID }}
      - 
        name: Trigger kubernetes deployment
        run: APP_VERSION=5750e4b kubectl kustomize ./devops/production/kubernetes
