name: "testastos"

on:
  push:
    branches:
      - "main"
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - 
        name: Save DigitalOcean kubeconfig
        run: doctl k8s cluster kubeconfig save ${{ secrets.DIGITALOCEAN_KUBERNETES_CLUSTER_ID }}
      -
        name: Retrieve load balancer external ip
        id: load-balancer-ip
        run: |
          $ip="$(kubectl get services --namespace traefik traefik --output jsonpath='{.status.loadBalancer.ingress[0].ip}')"
      - 
        name: Display load balancer IP
        run: |
          echo "The load balancer IP is [${{ steps.load-balancer-ip.outputs.external-ip }}]"
