name: "testing-bucket-configuration"

on:
  push:
    branches:
      - "**"

jobs:
  testing_configu:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      -
        name: Terraform init
        run: |
          terraform -chdir="devops/bucket" \
            init \
            -backend-config="access_key=${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.DIGITALOCEAN_SPACES_SECRET_ACCESS_KEY }}" \
            -backend-config="bucket=${{ secrets.DIGITALOCEAN_SPACES_TERRAFORM_STATES_BUCKET }}" \   
      -
        name: Terraform plan
        run: /
          terraform -chdir="devops/bucket" \
            plan
      
