name: "testing-bucket-configuration"

on:
  push:
    branches:
      - "**"
defaults:
  run:
    working-directory: devops/bucket
jobs:
  testing_config:
    env: 
      TF_VAR_DOPPLER_ACCESS_TOKEN_TRUSTUP_IO_CI_COMMONS: "${{ secrets.DOPPLER_ACCESS_TOKEN_TRUSTUP_IO_CI_COMMONS }}"
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      -
        name: Terraform init
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.DIGITALOCEAN_SPACES_SECRET_ACCESS_KEY }}" \
            -backend-config="bucket=${{ secrets.DIGITALOCEAN_SPACES_TERRAFORM_STATES_BUCKET }}"
      -
        name: Terraform plan
        run: terraform plan
      -
        name: Terraform apply
        run: terraform apply -auto-approve
      
