name: "testastos"

on:
  push:
    branches:
      - "main"
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - 
        name: Save DigitalOcean kubeconfig
        run: doctl k8s cluster kubeconfig save ${{ secrets.DIGITALOCEAN_KUBERNETES_CLUSTER_ID }}
      -
        name: Retrieve load balancer external ip
        id: load_balancer_ip
        run: |
          echo "external_ip=$(kubectl get services --namespace traefik traefik --output jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT
      - 
        name: Update DNS record
        uses: rez0n/create-dns-record@v2.1
        with:
          type: "A"
          name: "monitoring.website.trustup.io"
          content: ${{ steps.load_balancer_ip.outputs.external_ip }}
          ttl: 1
          proxied: true
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_DNS_ZONE_TRUSTUP_IO }}

